:construction_worker: adding heroku deployment

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -98,6 +98,23 @@ jobs:
             docker push $IMAGE_NAME:$CIRCLE_BUILD_NUM
             docker push $IMAGE_NAME:latest
 
+  back-deploy-heroku:
+    docker:
+      - image: buildpack-deps:trusty
+    steps:
+      - checkout
+      - run:
+          name: Heroku Deploy
+          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:main
+      - run:
+          name: Smoke Test
+          command: |-
+            HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://$HEROKU_APP_NAME.herokuapp.com/`
+            if [ "$HTTPCODE" -ne 200 ];then
+              echo "heroku app not responding, failing deploy"
+              exit 1
+            fi
+
 workflows:
   version: 2
   build-test-back-and-db:
@@ -107,6 +124,10 @@ workflows:
           requires:
             - initial-build
       - dockerhub-publishing:
+          requires:
+            - initial-build
+            - setup-and-test-db
+      - back-deploy-heroku:
           requires:
             - initial-build
             - setup-and-test-db
